Repository canonical/haproxy-operator, pull requests merged in 2025-07, with the labels that each got.

#150 ISD-3795 update certificate handling, update tests, request cert for haproxy-route backends using subdomains
  src/charm.py
  src/haproxy.py
  src/state/haproxy_route.py
  src/tls_relation.py
  tests/unit/conftest.py
  tests/unit/test_haproxy_route_state.py
Labels: Libraries: OK, senior-review-required

#152 ISD-3826 Update lib to add hostname and additional hostnames attribute, update haproxy logic to handle new attributes
  lib/charms/haproxy/v1/haproxy_route.py
  src/charm.py
  src/state/haproxy_route.py
  src/state/tls.py
  tests/integration/haproxy_route_requirer.py
  tests/integration/test_haproxy_route.py
  tests/unit/conftest.py
  tests/unit/test_haproxy_route_lib.py
  tests/unit/test_haproxy_route_scenario.py
  tests/unit/test_haproxy_route_state.py
  tests/unit/test_tls_relation.py
Labels: Libraries: OK, senior-review-required

#159 Fix docs according to vale lints
  README.md
  charmcraft.yaml
  docs/explanation/high-availability.md
  docs/getting-started.md
  docs/how-to/configure-virtual-ip-on-openstack.md
  docs/index.md
Labels: documentation, trivial

#162 Add "s" suffix to timeout entries
  templates/haproxy_route.cfg.j2
Labels: trivial
