Repository canonical/haproxy-operator, pull requests merged in 2025-08, with the labels that each got.

#166 render retry configuration in template, remove retry_interval attribute
  lib/charms/haproxy/v1/haproxy_route.py
  templates/haproxy_route.cfg.j2
  tests/integration/conftest.py
  tests/integration/helper.py
  tests/integration/legacy/conftest.py
  tests/integration/legacy/haproxy_route_requirer.py
  tests/integration/test_haproxy_route.py
Labels: trivial

#171 ISD-3954 add consistent hashing
  lib/charms/haproxy/v1/haproxy_route.py
  src/state/haproxy_route.py
  templates/haproxy_route.cfg.j2
  tests/integration/conftest.py
  tests/integration/test_haproxy_route.py
  tests/unit/legacy/test_haproxy_route_lib.py
Labels: trivial

#178 Add changelog
  .github/pull_request_template.yaml
  CHANGELOG.md
  docs/changelog.md
Labels: documentation, trivial

#177 Isd 3937 render haproxy route tcp relation data
  .github/workflows/integration_test.yaml
  charmcraft.yaml
  lib/charms/haproxy/v0/haproxy_route_tcp.py
  src/charm.py
  src/haproxy.py
  src/state/charm_state.py
  src/state/haproxy_route.py
  src/state/haproxy_route_tcp.py
  src/state/tls.py
  templates/haproxy_route.cfg.j2
  templates/haproxy_route_tcp.cfg.j2
  tests/integration/conftest.py
  tests/integration/haproxy_route_requirer.py
  tests/integration/haproxy_route_tcp_requirer.py
  tests/integration/test_haproxy_route_tcp.py
  tests/unit/legacy/test_state.py
  tests/unit/test_state.py
  tox.ini
Labels: senior-review-required

#187 ISD-3929 Use /dev/log for logging
  templates/haproxy.cfg.j2
Labels: trivial

#74 Implement the requirer side of the certificate transfer interface
  charmcraft.yaml
  lib/charms/certificate_transfer_interface/v1/certificate_transfer.py
  src/charm.py
  src/haproxy.py
  src/tls_relation.py
  tests/integration/conftest.py
  tests/integration/legacy/conftest.py
  tests/unit/conftest.py
  tests/unit/legacy/test_tls_relation.py
  tests/unit/test_charm.py
Labels: complex
