Repository canonical/haproxy-operator, pull requests merged in 2025-02, with the labels that each got.

#63 Allow the whole team to approve dependencies updates
  CODEOWNERS
Labels: Libraries: Out of sync

#66 add docs index
  docs/index.md
Labels: documentation, Libraries: Out of sync, trivial

#67 Improvements to handling certs, update template to handle ipv6
  src/charm.py
  src/state/validation.py
  templates/haproxy_ingress.cfg.j2
Labels: complex, Libraries: Out of sync
